owner: vankhoaluong
repo: uptime-monitor

sites:
  - name: All Telegram Bots
    url: https://multi-telegram-bot.onrender.com
    expectedStatus: 200
    checkInterval: 300

status-website:
  name: Trạng Thái Bot Telegram
  baseUrl: /uptime-monitor
  i18n:
    active: 🟢 Đang hoạt động
    down: 🔴 Đang gặp sự cố
    degraded: 🟡 Hiệu suất giảm

assignees:
  - vankhoaluong

delay: 300
requestTimeout: 10000
